name: mypda
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ffmpeg
  - moviepy
  - numpy
  - opt-einsum
  - pillow
  - pip
  - python=3.12
  - pytorch
  - pyyaml
  - scikit-image
  - setuptools
  - timm
  - torchaudio
  - torchvision
  - xformers
  - lightning
  - h5py
  - tyro
  - termcolor
  - matplotlib
  - ipdb
  - einops
  - tqdm
  - pip:
    - opencv_contrib_python==4.10.0.84
    - raft
    - wget

